<div class="panel panel-default" style="text-align: justify">
	<div class="panel-heading">
		<div class="panel-title">
			<h1>Twadar Terms of Service</h1>
		</div>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-12">
				<p>
					These terms and conditions ("Terms of Service") govern your access to and use of Social Media Frontiers Limited SLA's ("Twadar") products,
					software, services, and web site (collectively "Services"), and any and all information, text, graphics, photos or other
					materials uploaded, downloaded, or appearing on the Services (collectively "Content"). By accessing and using the Services,
					you are agreeing to be bound by these Terms of Service. If you do not agree to be bound by these Terms of Service, you are
					not allowed to use the Services. Wherever used in these Terms of Service, "you", "your" or similar terms mean the person or
					legal entity utilizing or accessing the Services.
				</p>
				<p>
					Social Media Frontiers Limited SLA may update and change the Terms of Service from time to time without notice. Continued use of the Service after
					any such changes shall constitute your consent to such changes. You are responsible for regularly reviewing the most current version
					of the Terms of Service. <!--which are currently available at: <a href="http://www.twadar.net/terms" target="_blank">http://www.twadar.net/terms</a>.-->
				</p>
				<p>
					These Terms of Service include Social Media Frontiers Limited SLA's privacy policy.<!-- which is currently available at:
					<a href="http://www.twadar.net/privacy" target="_blank">http://www.twadar.net/privacy</a>.--> By accessing and using the Services you are
					consenting to (or promising that you have obtained appropriate consent for) the	collection and use of personal information by Social Media Frontiers Limited SLA
					in accordance with the privacy policy of Social Media Frontiers Limited SLA.
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<ul>
					<li><a href="#basic-terms">Basic Terms</a></li>
					<li><a href="#your-account">Your Account</a></li>
					<li><a href="#use-and-restrictions">Use and Restrictions</a></li>
					<li><a href="#accessed-content">Content</a></li>
					<li><a href="#payment-matters">Payment Matters</a></li>
					<li><a href="#modifications-to-the-services-and-prices">Modifications to the Services and Prices</a></li>
					<li><a href="#cancellation-and-termination">Cancellation and Termination</a></li>
					<li><a href="#ownership-and-licenses">Ownership and Licenses</a></li>
					<li><a href="#disclaimer-and-limitation-of-liability">Disclaimer and Limitation of Liability</a></li>
					<li><a href="#general-conditions">General Conditions</a></li>
				</ul>
			</div>
		</div>
		<div id="basic-terms" class="row">
			<div class="col-md-12">
				<h2>Basic Terms</h2>
				<ol>
					<li>
						You are responsible for your use of the Services and for any Content accessed or made available to others through your account
						(even if that Content is accessed or made available by others). You take all risks associated with the Services and any Content
						accessed or made available to others through your account. Social Media Frontiers Limited SLA will not be held responsible for your use of the Services
						or for any such Content.
					</li>
					<li>
						To access or use the Services, you must be able to form a binding contract with Social Media Frontiers Limited SLA and you must not be prohibited from
						receiving the Services under United Kingdom law or any other applicable laws.
					</li>
					<li>
						Social Media Frontiers Limited SLA may change the Services or stop providing them (temporarily or permanently) at any time and from time to time without notice.
					</li>
					<li>
						You acknowledge that the Services allow you to access and use content and services offered by third party service providers (e.g., Twitter,
						Facebook) ("Third Party Service Providers"). You must agree to comply with the relevant terms and conditions of any such Third Party Service Provider.
					</li>
					<li>
						Your access to and use of the Services must be in accordance with these Terms of Service. If you violate these Terms of Service, you are no
						longer permitted to use the Services and Social Media Frontiers Limited SLA may (but has no obligation to) terminate your ability to access or use the Services at any time.
					</li>
				</ol>
			</div>
		</div>
		<div id="your-account" class="row">
			<div class="col-md-12">
				<h2>Your Account</h2>
				<ol>
					<li>
						You must provide your legal full name, a valid email address, and any other information requested in order to complete the account sign-up process.
					</li>
					<li>
						You are responsible for maintaining the security of your account login information and for any activities or actions occurring under your account.
						Social Media Frontiers Limited SLA encourages you to use a "strong" password (passwords that use a combination of upper and lower case letters, numbers and symbols) for
						your account. Social Media Frontiers Limited SLA will not be responsible for any loss or damages resulting from your failure to comply with this obligation.
					</li>
					<li>
						Each account login may only be used by one person - a single login shared by multiple people is not permitted. You may create separate logins for your
						account for as many people as you'd like.
					</li>
					<li>
						You must be a human. Accounts registered by "bots" or other automated methods are not permitted.
					</li>
					<li>
						One person or legal entity may not maintain more than one free account.
					</li>
				</ol>
			</div>
		</div>
		<div id="use-and-restrictions" class="row">
			<div class="col-md-12">
				<h2>Use and Restrictions</h2>
				<ol>
					<li>
						You may only use the Services to: (a) access Content on Social Media Frontiers Limited SLA's website; and (b) access, manage and obtain information about your accounts
						with Third Party Service Providers in accordance with these Terms of Service and any terms specified by the Third Party Service Providers.
					</li>
					<li>
						You may not access or search or attempt to access or search the Services by any means (automated or otherwise) except through Social Media Frontiers Limited SLA's
						currently available interfaces.
					</li>
					<li>
						You may not use the Services for any illegal or unauthorized purpose, including in any way that violates copyright or other laws applicable in
						United Kingdom or applicable to you.
					</li>
					<li>
						You may not use the Services in a way that is detrimental to the operation of the Services or the access or use of the Services by anyone else.
						This restriction applies to any use that interferes or attempts to interfere with the normal operations of the Services, including by hacking,
						deleting, augmenting or altering the Services or any Content.
					</li>
					<li>
						You may not, without Social Media Frontiers Limited SLA's prior written permission (including the permissions granted by these Terms of Service): (a) copy,
						distribute (including by framing any of the Services on any web site), modify, enhance, translate, reproduce, sell, resell, sublicense, rent,
						lease, or otherwise attempt to exploit the Services; (b) decompile, disassemble, reverse engineer, or otherwise attempt to discover the source
						code (except to the extent that this restriction is expressly prohibited by law); (c) make derivative works of the Services; or (d) modify
						another website so as to falsely imply that it is associated with the Services, Social Media Frontiers Limited SLA or any other Social Media Frontiers Limited SLA products or services.
					</li>
				</ol>
			</div>
		</div>
		<div id="accessed-content" class="row">
			<div class="col-md-12">
				<h2>Content</h2>
				<ol>
					<li>
						You understand that by using the Services you may be exposed to Content that might be unlawful, offensive, harmful, inaccurate, or otherwise
						inappropriate or deceptive. Social Media Frontiers Limited SLA does not pre-screen Content and cannot be responsible for the Content accessed or made available to
						others through the Services.
					</li>
					<li>
						Social Media Frontiers Limited SLA and its designees have the right (but not the obligation) in their sole discretion to refuse or remove any Content that is
						available via the Services. Social Media Frontiers Limited SLA may (but has no obligation to) remove Content and accounts containing Content that Social Media Frontiers Limited SLA
						determines in its sole discretion to be unlawful, offensive, harmful, inaccurate, or otherwise inappropriate or deceptive (including Content
						that Social Media Frontiers Limited SLA determines in its sole discretion to: (a) be libelous, defamatory, pornographic, obscene, or otherwise objectionable; or
						(b) violate any party's intellectual property).
					</li>
					<li>
						Social Media Frontiers Limited SLA does not permit verbal, physical, written or other abuse (including threats of abuse or retribution) of any Social Media Frontiers Limited SLA
						customer, employee, member, or officer. Engaging in any such behaviour may at Social Media Frontiers Limited SLA's sole discretion result in the immediate
						termination or your account.
					</li>
					<li>
						You must not upload, post, host, transmit or otherwise make available to others unsolicited email, SMSs, or "spam" messages through the Services.
					</li>
					<li>
						You must not transmit or otherwise make available to others any worms or viruses or any code of a destructive nature ("Viruses") through the Services.
					</li>
				</ol>
			</div>
		</div>
		<div id="payment-matters" class="row">
			<div class="col-md-12">
				<h2>Payment Matters</h2>
				<ol>
					<li>
						If you are purchasing Services from Social Media Frontiers Limited SLA, you must provide Social Media Frontiers Limited SLA with a valid credit card or other payment method accepted
						by Social Media Frontiers Limited SLA.
					</li>
					<li>
						If you sign up for an account with a free initial trial period, and you do not cancel that account within the first 30 days after it was
						initially created, you will automatically be billed monthly starting on the 30th day after your account was initially created. If you cancel
						your account prior to the beginning of the 30th day, you will not be charged.
					</li>
					<li>
						Purchased Services are billed in advance on a monthly or yearly basis (as per the option you have chosen) and are non-refundable. This means
						that there will be no refunds for partial months (or years) of service, or for months where the Services were unused.
					</li>
					<li>
						All fees are exclusive of taxes, levies, withholdings or duties imposed by taxing authorities, and you shall be responsible for payment
						of all such taxes, levies, withholdings or duties in addition to the fees.
					</li>
					<li>
						You must fill out your correct province/state and country so that Social Media Frontiers Limited SLA can understand its obligations to applicable taxation authorities.
					</li>
				</ol>
			</div>
		</div>
		<div id="modifications-to-the-services-and-prices" class="row">
			<div class="col-md-12">
				<h2>Modifications to the Services and Prices</h2>
				<ol>
					<li>
						Social Media Frontiers Limited SLA may change the Services at any time and from time to time without notice. Any changes to the Services, including releases of
						new features, tools or resources, shall be subject to these Terms of Service. Social Media Frontiers Limited SLA may also stop (temporarily or permanently) providing
						the Services (or any part of the Services) to you or to its customers generally without prior notice.
					</li>
					<li>
						Prices of all Services, including but not limited to monthly subscription plan fees for Services, are subject to change upon 30 days notice
						from Social Media Frontiers Limited SLA. Such notice may be provided at any time by posting the changes on Twadar's website (currently located at
						<a href="http://www.twadar.net" target="_blank">http://www.twadar.net</a>).
					</li>
					<li>
						Social Media Frontiers Limited SLA shall not be liable to you or to any third party for any change to the Services, price change, suspension or discontinuance of
						the Services.
					</li>
				</ol>
			</div>
		</div>
		<div id="cancellation-and-termination" class="row">
			<div class="col-md-12">
				<h2>Cancellation and Termination</h2>
				<ol>
					<li>
						Your cancellation will take effect immediately and Social Media Frontiers Limited SLA will delete all of your Content from the Services reasonably promptly
						after cancellation. Once you cancel your account, your Content cannot be recovered.
					</li>
					<li>
						Social Media Frontiers Limited SLA does not accept any responsibility for loss of Content due to account cancellation.
					</li>
					<li>
						Social Media Frontiers Limited SLA, in its sole discretion, has the right to suspend, terminate or restrict your access to the Services, or any other Twadar
						Limited service, for any reason and at any time. Such termination of the Services will result in the deactivation or deletion of your
						account or your access to your account, and the deletion of all Content on your account. Social Media Frontiers Limited SLA reserves the right to refuse to
						provide the Services to anyone for any reason at any time.
					</li>
					<li>
						The provisions regarding "Use and Restrictions", "Payment Matters", "Cancellation and Termination", "Ownership", "Disclaimer and
						Limitation of Liability" and "General" and any provisions which by their nature survive, shall survive the termination of these Terms of Service.
					</li>
				</ol>
			</div>
		</div>
		<div id="ownership-and-licences" class="row">
			<div class="col-md-12">
				<h2>Ownership and Licenses</h2>
				<ol>
					<li>
						Social Media Frontiers Limited SLA and its licensors retain title to and ownership of all rights (including copyright, trade-mark, patent, trade secret and all
						other intellectual property rights) in and to the Services and Social Media Frontiers Limited SLA's Content. You acquire no rights whatsoever to all or any part
						of the Services except for the limited use rights granted by these Terms of Service. All rights not expressly granted to you are reserved to
						Social Media Frontiers Limited SLA and its licensors.
					</li>
					<li>
						We claim no intellectual property rights over the Content made available to others through your account. Additionally, your profile and
						other Content you provide to Social Media Frontiers Limited SLA in connection with the Services remain yours. However, by making that Content available to others
						through the Services, or providing it to Social Media Frontiers Limited SLA through the Services, you grant Social Media Frontiers Limited SLA a worldwide, non-exclusive, royalty-free,
						fully paid up license (with a right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute
						such Content through any or all media or distribution methods (whether now known or hereafter developed). You also acknowledge that the purpose
						of the Services is to access the services of Third Party Service Providers, and that as a result you are agreeing to grant to Social Media Frontiers Limited SLA
						any and all other rights you grant to applicable Third Party Service Providers.
					</li>
					<li>
						When using the Service, you agree that you are following the relevant terms and conditions of the Third Party Service Provider you are accessing.
					</li>
				</ol>
			</div>
		</div>
		<div id="disclaimer-and-limitation-of-liability" class="row">
			<div class="col-md-12">
				<h2>Disclaimer and Limitation of Liability</h2>
				<p>
					THE SERVICES ARE PROVIDED "AS IS", "AS AVAILABLE", WITH ALL FAULTS AND WITHOUT WARRANTIES, REPRESENTATIONS OR CONDITIONS OF ANY KIND. USE OF THE SERVICES
					IS ENTIRELY AT YOUR OWN RISK. Social Media Frontiers Limited SLA DOES NOT MAKE ANY REPRESENTATIONS, WARRANTIES OR CONDITIONS ABOUT THE QUALITY, ACCURACY, SECURITY, RELIABILITY,
					COMPLETENESS, QUIET ENJOYMENT, CURRENCY, OR TIMELINESS OF THE SERVICES. Social Media Frontiers Limited SLA DOES NOT ASSUME ANY RESPONSIBILITY FOR ANY INCOMPLETENESS, ERRORS,
					SECURITY, VIRUSES, BUGS, PROBLEMS, OMISSIONS, INACCURACIES OR OTHER LIMITATIONS IN, OR INTERRUPTIONS IN THE OPERATION OF, THE SERVICES.
				</p>
				<p>
					TO THE FULLEST EXTENT PERMITTED BY LAW, Social Media Frontiers Limited SLA DISCLAIMS ALL WARRANTIES, REPRESENTATIONS AND CONDITIONS OF ANY KIND WITH RESPECT TO THE SERVICES
					WHETHER EXPRESS, IMPLIED OR COLLATERAL, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
					PURPOSE AND NON-INFRINGEMENT OR THAT THE SERVICES ARE OR WILL BE SECURE, COMPLETE OR FREE OF ERRORS, VIRUSES, BUGS, PROBLEMS OR OTHER LIMITATIONS OR WILL
					OPERATE WITHOUT INTERRUPTION. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW. Social Media Frontiers Limited SLA DISCLAIMS ALL LIABILITY, WHETHER BASED ON
					WARRANTY, CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE, GROSS NEGLIGENCE OR WILFUL MISCONDUCT), PRODUCT LIABILITY, STRICT LIABILITY, STATUTORY
					LIABILITY, BREACH OF A FUNDAMENTAL TERM, FUNDAMENTAL BREACH, OR ANY OTHER LEGAL THEORY, FOR ANY LOSS OR DAMAGES OF ANY KIND (INCLUDING, WITHOUT LIMITATION
					ANY (I) DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE LOSS OR DAMAGE, (II) LOST PROFITS OR SAVINGS, (III) BUSINESS INTERRUPTION,
					(IV) LOSS OF PROGRAMS OR DATA (INCLUDING ANY CONTENT), (V) LOST REVENUE OR FAILURE TO REALIZE EXPECTED SAVINGS, (VI) LOSS OF USE, (VII) PERSONAL INJURY,
					(VIII) FINES, FEES, PENALTIES, OR (VI) ANY OTHER LOSSES OR DAMAGES WHETHER OR NOT Social Media Frontiers Limited SLA IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING
					FROM THE USE OF, OR THE INABILITY TO MAKE USE OF, THE SERVICES.
				</p>
			</div>
		</div>
		<div id="general-conditions" class="row">
			<div class="col-md-12">
				<h2>General Conditions</h2>
				<ol>
					<li>
						Technical support is only provided to paying account holders and is only available via email. The section below entitled "Social Media Frontiers Limited SLA SLA"
						describes Social Media Frontiers Limited SLA's objectives for response and resolution times and includes, where appropriate, your sole remedy for a failure to meet
						these objectives.
					</li>
					<li>
						You understand that Social Media Frontiers Limited SLA uses third party vendors and hosting partners to provide the necessary hardware, software, networking,
						storage, and related technology required to run the Services.
					</li>
					<li>
						You understand that the technical processing and transmission of the Services, including your Content, may be transferred unencrypted
						and involve: (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.
					</li>
					<li>
						If your bandwidth usage exceeds 300 MB/month, or significantly exceeds the average bandwidth usage of other Social Media Frontiers Limited SLA customers (as determined
						by Social Media Frontiers Limited SLA in its sole discretion), Social Media Frontiers Limited SLA reserves the right to immediately disable or impose restrictions upon your account until
						you reduce your bandwidth consumption.
					</li>
					<li>
						The failure of Social Media Frontiers Limited SLA to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right
						or provision. The Terms of Service constitutes the entire agreement between you and Social Media Frontiers Limited SLA and governs your use of the Services, superseding
						any prior agreements between you and Social Media Frontiers Limited SLA (including, but not limited to, any prior versions of the Terms of Service). A printed version
						of these Terms of Service and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or
						relating to these Terms of Service to the same extent and subject to the same conditions as other business documents and records originally generated
						and maintained in printed form. Subject to Social Media Frontiers Limited SLA's ability to amend these Terms of Service, they cannot be changed.
					</li>
					<li>
						If any of the provisions contained in these Terms of Service are determined to be void, invalid or otherwise unenforceable by a court of law, that
						provision shall be enforced to the maximum extent permissible so as to effect the intent of these Terms of Service and such determination shall not
						affect the remaining provisions contained herein.
					</li>
					<li>
						You may not assign these Terms of Service or any of your rights or obligations under these Terms of Service to a third party. Subject to the
						foregoing, these Terms of Service shall ensure to the benefit of and be binding upon you and Social Media Frontiers Limited SLA and their respective successors
						(including any successor by reason of amalgamation) and assigns.
					</li>
					<li>
						You agree that if you sue Social Media Frontiers Limited SLA and do not obtain judgment in your favour, you will pay all of Social Media Frontiers Limited SLA's costs, including
						reasonable fees for in-house and outside legal counsel.
					</li>
					<li>
						These Terms of Service are governed by the laws of the United Kingdom and all disputes or other matters arising out of this License will
						be dealt with by a court of law, United Kingdom. These laws apply to your access to or use of the Services, notwithstanding your domicile,
						residency or physical location. The Services are intended for use only in jurisdictions where they may lawfully be offered for use. You and
						Social Media Frontiers Limited SLA specifically disclaim the UN Convention on Contracts for the International Sale of Goods.
					</li>
				</ol>
			</div>
		</div>
	</div>
</div>